apiVersion: v1
kind: Pod
metadata:
  name: title
  labels:
    role: title
spec:
  containers:
    - name: monaco-build
      image: golang:latest
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: "100m"
          memory: "1Gi"
        limits:
          cpu: "2"
          memory: "16Gi"
